### ISSUE TITLE
AttributeError: module 'scope_gui' has no attribute 'ScopeWindow'

### ISSUE THREAD

**Issue by Lovro7a** [eilmi/HAMEG-HM1007-serial-interface#3]
When I run the program in VS Code, I get this error:

`Traceback (most recent call last):
  File "c:\Users\Lovro\Desktop\hameg_interface\main.py", line 232, in <module>
    main()

  File "c:\Users\Lovro\Desktop\hameg_interface\main.py", line 227, in main
    app = App(root)
          ^^^^^^^^^
  File "c:\Users\Lovro\Desktop\hameg_interface\main.py", line 196, in __init__
    self.scopewindow = scope_gui.ScopeWindow(self)
                       ^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'scope_gui' has no attribute 'ScopeWindow'
`

How can I fix this?

**Comment by eilmi** [comment]
Just tried it on an completely fresh Win11 install and it works after some problems not really related to this project....

Had to install Microsoft Visual C++ redistributable as described in https://kiwisolver.readthedocs.io/en/latest/basis/installation.html

and
pip install msvc-runtime

but after that, it starts without any problems


maybe you could provide a little bit more information?

**Comment by Lovro7a** [comment]
I installed Microsoft Visual C++ and the MSVC runtime.

I still get the same error.


In the first picture (error picture 1) is the line of code with the mistake
in main.py.

In the second picture is the class. It is in scope_gui.py.

The third picture shows the folder with the files.

The folder "main" contains the program for Arduino in the Arduino IDE.

The folder "slike" is just a folder with 3 pictures from this email.


I have also tried to copy-paste the name and it didn't work.


When I get this part of the project working, I will make a PCB with the
ATmega328 and FT232 (USB to UART) so I don't need to use the Arduino. If
you want, I can send the Gerber files and schematics to you.

V V tor., 25. jun. 2024 ob 22:40 je oseba Philipp Eilmsteiner <
***@***.***> napisala:

**Comment by Lovro7a** [comment]
Sorry, I forgot to upload the images to the email I sent you before.

![napaka slika mapa](https://github.com/eilmi/HAMEG-HM1007-serial-interface/assets/171515300/a3cfbc99-812d-49b3-b951-64f869dbc8f1)
![napaka slika1](https://github.com/eilmi/HAMEG-HM1007-serial-interface/assets/171515300/5f8febd6-385b-4e14-a088-31e6617e2e5f)
![napaka slika2](https://github.com/eilmi/HAMEG-HM1007-serial-interface/assets/171515300/877c24cd-c0ab-44cf-b216-8cb7210aa3bd)

**Comment by eilmi** [comment]
I'm sorry but this is definitely a problem on your side, because as I already said, it's working on a brand new Win11 install and under Linux without any problems.

Maybe just try cloning the repository again, because your File-Explorer is reporting 0kB file sizes for scope_gui.py, settings_gui.py and signalinfo_gui.py which can't be right.

**Comment by eilmi** [comment]
Just download the zip file containing all the files of the repository:

https://github.com/eilmi/HAMEG-HM1007-serial-interface/archive/refs/heads/main.zip

**Comment by eilmi** [comment]
closing the issue because there isn't a problem with the project
